{{--
    Token usage overview — helps developers see how much Copilot CLI usage
    (token consumption) they are driving, so they can keep it in check.

    Variables expected:
    $summary    — array from UsageReportService::summary()
    $timeSeries — array of buckets incl. prompt_tokens / output_tokens / tokens
--}}
@php
    $totalTokens  = $summary['cli_total_tokens'] ?? 0;
    $promptTokens = $summary['cli_prompt_tokens'] ?? 0;
    $outputTokens = $summary['cli_output_tokens'] ?? 0;
    $cliRequests  = $summary['cli_requests'] ?? 0;
    $avgPerRequest = $cliRequests > 0 ? round($totalTokens / $cliRequests) : 0;
    $hasTokenTrend = array_sum(array_column($timeSeries, 'tokens')) > 0;
@endphp

<div class="card" style="margin-bottom:16px;">
    <div class="card-header">
        Token usage
        <span style="font-weight:400; color:var(--muted); font-size:11px;">Copilot CLI prompt &amp; output tokens</span>
    </div>
    <div class="card-body">
        <div class="stats-grid" style="margin-bottom:0;">
            <div class="stat-card">
                <div class="label">Total tokens</div>
                <div class="value" style="color: var(--orange)">{{ number_format($totalTokens) }}</div>
                <div class="sub">prompt + output</div>
            </div>
            <div class="stat-card">
                <div class="label">Prompt tokens</div>
                <div class="value" style="color: var(--accent)">{{ number_format($promptTokens) }}</div>
                <div class="sub">sent to the model</div>
            </div>
            <div class="stat-card">
                <div class="label">Output tokens</div>
                <div class="value" style="color: var(--purple)">{{ number_format($outputTokens) }}</div>
                <div class="sub">generated by the model</div>
            </div>
            <div class="stat-card">
                <div class="label">Avg tokens / request</div>
                <div class="value">{{ number_format($avgPerRequest) }}</div>
                <div class="sub">{{ number_format($cliRequests) }} CLI requests</div>
            </div>
        </div>
    </div>
</div>

<div class="card" style="margin-bottom:16px;">
    <div class="card-header">Token usage over time</div>
    <div class="card-body chart-wrap">
        @if($hasTokenTrend)
            @php
                $promptTrend = [];
                $outputTrend = [];
                foreach ($timeSeries as $r) {
                    $promptTrend[$r['label']] = $r['prompt_tokens'];
                    $outputTrend[$r['label']] = $r['output_tokens'];
                }
            @endphp
            {!! \Noeka\Svgraph\Chart::bar()
                ->theme($chartTheme)
                ->addSeries(\Noeka\Svgraph\Data\Series::of('Prompt', $promptTrend, '#58a6ff'))
                ->addSeries(\Noeka\Svgraph\Data\Series::of('Output', $outputTrend, '#bc8cff'))
                ->stacked()
                ->axes()->grid()->legend() !!}
        @else
            <div class="empty-state"><p>No token usage recorded for this period.<br>Token data is reported for Copilot CLI usage.</p></div>
        @endif
    </div>
</div>
